### ISSUE TITLE
Help,  Mac Cannot not open Mpsyt (error msg attached)

### ISSUE THREAD

**Issue by vacarogit** [mps-youtube/yewtube#1087]
## Your Environment
Proper functional Hackintosh in High Sierra, last time mpsyt works

Errors in terminal:

$mpsyt
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /usr/local/bin/mpv
  Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/mps_youtube/init.py", line 67, in init
    load_player_info(config.PLAYER.get)
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/mps_youtube/util.py", line 408, in load_player_info
    g.mpv_version = _get_mpv_version(player)
  File "/usr/local/Cellar/mps-youtube/0.2.8_10/libexec/lib/python3.8/site-packages/mps_youtube/util.py", line 446, in _get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mpv', '--version']' died with <Signals.SIGABRT: 6>.

**Comment by Amar1729** [comment]
Looks like something's wrong with mpv. Try `brew reinstall mpv` and the paste the output of `mpv --version`. 

Also, you should use code block formatting for terminal output (surround with triple backtics `)
