### ISSUE TITLE
mpsyt crashes on completing or closing video

### ISSUE THREAD

**Issue by acerbicless** [mps-youtube/yewtube#1098]
Whenever a video finishes (mpv exits automatically on video end) or if the mpv video player is closed mpsyt exits with the below information. mpsyt has to be started again.

`Traceback (most recent call last): 00:00:02 [0%]   [
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.8/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/usr/lib/python3.8/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 79, in play
    self._playsong()
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 138, in _playsong
    self._launch_player()
  File "/usr/lib/python3.8/site-packages/mps_youtube/player.py", line 298, in _launch_player
    self.launch_player(cmd)
  File "/usr/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 134, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/usr/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 187, in _player_status
    if resp['data'] is not None:
KeyError: 'data'
`

Running on arch - kernel 5.6.15
mpsyt version: 0.2.8
pafy version: 0.5.5 (youtube-dl backend)
youtube-dl version: 2020.06.16.1
Python version: 3.8.3
mpv version: 0.32.0-526-g102a083171

**Comment by gaurav-dixitv** [comment]
#1092 fixes this.
