### ISSUE TITLE
Crash when playing any search result

### ISSUE THREAD

**Issue by V10lator** [mps-youtube/yewtube#1170]
```
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1672, in _real_extract
    token = video_info.get('token') or video_info.get('account_playback_token')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by andrewelkin** [comment]
I have the same issue..

**Comment by kiketson** [comment]
Also the same issue. Any news on how to solve this?

**Comment by iamtalhaasghar** [comment]
Update to the latest version.
