### ISSUE TITLE
yt-dlp problem from yewtube player

### ISSUE THREAD

**Issue by tom-i** [mps-youtube/yewtube#1225]
yewtube has some weird error when I wanted to play some YTB content.
Also "**Stremed**" content is not playable.

## Issue / Suggestion

Steps to repro:
1. Run `yt`
2. Search `/abgt 519`
3. try to run some "**Streamed**" music
```
Exception in thread Thread-2 (_preload):
Traceback (most recent call last):
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3605, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1218, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 692, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [youtube] v7HDJjv2KZA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/streams.py", line 189, in _preload
    streamlist = get(song)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/streams.py", line 54, in get
    ps = pafy.get_video_streams(ytid)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/pafy.py", line 43, in get_video_streams
    info_dict = ydl.extract_info(ytid, download=False)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1432, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 978, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/tomasi/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 921, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] v7HDJjv2KZA: Unable to extract uploader id
```

## Your Environment

Installed `yewtube` version:
```
└─(12:01:53)──> yt --version
yewtube version    : 2.10.2
yt_dlp version     : 2022.08.14
Python version     : 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Processor          :
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-6.2.8-arch1-1-x86_64-with-glibc2.37
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/tomasi/.config/mps-youtube
dbus               : 1.3.2
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
```
Installed `yt-dlp` via `pipx`
```
└─(12:01:45)──> yt-dlp -U
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
```

Installed `yt-dlp` from AUR:
```
aur/yt-dlp-git 2023.03.03.r6.g283a0b5bc-1 (+35 3.68) (Installed: 2023.03.04.r55.gab92d8651-1)                                                                                                                                          /0.7s
```

**Comment by diggidong** [comment]
you need to [update yt-dlp from within yewtube virtenv](https://github.com/iamtalhaasghar/yewtube/wiki/Common-issues#3-how-to-update-yt-dlp-to-latest-version) with: 
```pipx runpip yewtube install -U yt-dlp```

**Comment by tom-i** [comment]
That helps.. thx so much :-)
