### ISSUE TITLE
unable to extract uploader id; please report this issue on github

### ISSUE THREAD

**Issue by tokisuno** [mps-youtube/yewtube#1228]
got this while trying to download a video

my environment:
![image](https://user-images.githubusercontent.com/85533116/236690077-97cccfdb-cb8a-493e-b436-739c6586c037.png)

```ERROR: [youtube] my7d7zjzFRo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Exception in thread Thread-6 (_preload):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3906, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 698, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [youtube] my7d7zjzFRo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/woopityscoop/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 189, in _preload
    streamlist = get(song)
  File "/home/woopityscoop/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 54, in get
    ps = pafy.get_video_streams(ytid)
  File "/home/woopityscoop/.local/lib/python3.10/site-packages/mps_youtube/pafy.py", line 43, in get_video_streams
    info_dict = ydl.extract_info(ytid, download=False)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1466, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 996, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 936, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] my7d7zjzFRo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U```

**Comment by iamtalhaasghar** [comment]
Update your yt-dlp,

**Comment by tokisuno** [comment]
dope yt
