### ISSUE TITLE
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; 

### ISSUE THREAD

**Issue by c0dehu1k** [mps-youtube/yewtube#1237]
Trying to use it first time

## Issue / Suggestion
open in terminal
search /test
and console shows this error

Search results for test                                                                                                                              
> ERROR: [youtube] M3ogGEey3WI: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Exception in thread Thread-1 (_preload):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3463, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

## Your Environment
I have the latest yt-dlp installed

➜  ~ yt-dlp --version
2023.06.22

Ubuntu 22.04
Kitty Terminal

**Comment by c0dehu1k** [comment]
➜  ~ yt --version
yewtube version    : 2.9.2
yt_dlp version     : 2022.04.08
Python version     : 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.15.0-76-generic-x86_64-with-glibc2.35
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/xxx/.config/mps-youtube
dbus               : 1.2.18
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_IN
➜  ~ yt-dlp --version
2023.06.22

Not sure why it showing old version of yt_dlp, I have new installed.

**Comment by iamtalhaasghar** [comment]
I just did a couple of searches and yewtube is working fine for me.

```$ yt --version
yewtube version    : 2.10.4
yt_dlp version     : 2023.03.04
Python version     : 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-6.3.8-200.fc38.x86_64-x86_64-with-glibc2.37
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/programmer/.config/mps-youtube
dbus               : 1.3.2
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
```

**Comment by c0dehu1k** [comment]
Yeah worked for me!
It was issue with 2 different version of yt-dlp installed at /usr/bin and /usr/local/bin.

Might help others, before raising an issue.
