### ISSUE TITLE
Error when starting the script

### ISSUE THREAD

**Issue by Jangsoodlor** [mps-youtube/yewtube#1267]
This happended when I tried to run the script, after a fresh install:
```
                                                                                        | |       | |
                                                                     _   _  _____      _| |_ _   _| |__   ___
                                                                    | | | |/ _ \ \ /\ / / __| | | | '_ \ / _ \
                                                                    | |_| |  __/\ V  V /| |_| |_| | |_) |  __/
                                                                     \__, |\___| \_/\_/  \__|\__,_|_.__/ \___|
                                                                      __/ |
                                                                     |___/
                                                                        v2.9.2


Enter /search-term to search or [h]elp
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jangsoodlor\AppData\Local\Programs\Python\Python311\Scripts\yt.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jangsoodlor\AppData\Local\Programs\Python\Python311\Lib\site-packages\mps_youtube\main.py", line 132, in main
    history.load()
  File "C:\Users\Jangsoodlor\AppData\Local\Programs\Python\Python311\Lib\site-packages\mps_youtube\history.py", line 24, in load
    g.userhist['history'] = read_m3u(g.HISTFILE)
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jangsoodlor\AppData\Local\Programs\Python\Python311\Lib\site-packages\mps_youtube\playlists.py", line 66, in read_m3u
    if plf.readline().startswith('#EXTM3U'):
       ^^^^^^^^^^^^^^
  File "C:\Users\Jangsoodlor\AppData\Local\Programs\Python\Python311\Lib\encodings\cp874.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 134: character maps to <undefined>
```
yewtube version    : 2.9.2
yt_dlp version     : 2023.12.30
Python version     : 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Processor          : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19045-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\Jangsoodlor\AppData\Roaming\mps-youtube
dbus               : None
glib               : False
env:LANG           : en_US.UTF-8
```
## My Environment
```
yewtube version    : 2.9.2
yt_dlp version     : 2023.12.30
Python version     : 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Processor          : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19045-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\Jangsoodlor\AppData\Roaming\mps-youtube
dbus               : None
glib               : False
env:LANG           : en_US.UTF-8
```

**Comment by iamtalhaasghar** [comment]
is this still happening?

**Comment by Jangsoodlor** [comment]
yes

**Comment by worldpoop** [comment]
I'm getting the same error, except on Mac 

```
Traceback (most recent call last):
  File "/Users/mau/.local/bin/yt", line 8, in <module>
    sys.exit(main.main())
             ~~~~~~~~~^^
  File "/Users/mau/.local/pipx/venvs/yewtube/lib/python3.13/site-packages/mps_youtube/main.py", line 118, in main
    init.init()
    ~~~~~~~~~^^
  File "/Users/mau/.local/pipx/venvs/yewtube/lib/python3.13/site-packages/mps_youtube/init.py", line 70, in init
    _init_readline()
    ~~~~~~~~~~~~~~^^
  File "/Users/mau/.local/pipx/venvs/yewtube/lib/python3.13/site-packages/mps_youtube/init.py", line 217, in _init_readline
    readline.read_history_file(g.READLINE_FILE)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
FileExistsError: [Errno 17] File exists
```
