### ISSUE TITLE
Corrupted cache data

### ISSUE THREAD

**Issue by marcusdavanco** [mps-youtube/yewtube#1272]
## Issue / Suggestion
Yesterday I exited yewtube using Ctrl + C multiple times, and when I tried to open it again, I'm receiving this output:

Traceback (most recent call last):
  File "/home/md/.local/bin/yt", line 8, in <module>
    sys.exit(main.main())
  File "/home/md/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/main.py", line 118, in main
    init.init()
  File "/home/md/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/init.py", line 71, in init
    cache.load()
  File "/home/md/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/cache.py", line 20, in load
    cached = pickle.load(cf)
_pickle.UnpicklingError: pickle data was truncated

I already reinstalled it, reinstalled pip and even reinstalled python but the problem persists.

## Your Environment
yewtube version    : 2.10.4
yt_dlp version     : 2024.04.09
Python version     : 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.10.0-28-amd64-x86_64-with-glibc2.31
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/md/.config/mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : pt_BR.UTF-8

mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
ffmpeg version: 4.3.6-0+deb11u1

Any advices on how to solve it?

**Comment by marcusdavanco** [comment]
In case anyone has a similar proble, deleting your config dir at  /home/user/.config/mps-youtube solves the issue.
