### ISSUE TITLE
"FIleExistsError: [Errno 17] File exists" when installing through homebrew

### ISSUE THREAD

**Issue by MickLib** [mps-youtube/yewtube#1274]
When installing yewtube through home-brew on macOS and running it it gives this error

Traceback (most recent call last):
  File "/opt/homebrew/bin/yt", line 8, in <module>
    sys.exit(main.main())
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yewtube/2.10.5_2/libexec/lib/python3.12/site-packages/mps_youtube/main.py", line 118, in main
    init.init()
  File "/opt/homebrew/Cellar/yewtube/2.10.5_2/libexec/lib/python3.12/site-packages/mps_youtube/init.py", line 70, in init
    _init_readline()
  File "/opt/homebrew/Cellar/yewtube/2.10.5_2/libexec/lib/python3.12/site-packages/mps_youtube/init.py", line 217, in _init_readline
    readline.read_history_file(g.READLINE_FILE)
FileExistsError: [Errno 17] File exists

## Your Environment
 macOS, Kitty terminal
 mpsyt not found
  14.4.1

**Comment by iamtalhaasghar** [comment]
Kindly paste yewtube version info,

**Comment by yougotwill** [comment]
Same issue with install using 2.10.5 via pipx and mpv installed via homebrew via /opt/homebrew
