### ISSUE TITLE
DownloadError [youtube] Sign in to confirm you’re not a bot. This helps protect our community. 

### ISSUE THREAD

**Issue by F1LT3R** [mps-youtube/yewtube#1276]
[1/2>
> ERROR: [youtube] PDOhr2GVcdc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
Exception in thread Thread-4 (_preload):
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] PDOhr2GVcdc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 189, in _preload
    streamlist = get(song)
  File "/home/user/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 54, in get
    ps = pafy.get_video_streams(ytid)
  File "/home/user/.local/lib/python3.10/site-packages/mps_youtube/pafy.py", line 43, in get_video_streams
    info_dict = ydl.extract_info(ytid, download=False)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1073, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1012, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] PDOhr2GVcdc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by mickeymarse** [comment]
Just got the same error here. A very bad start to my day. :(

**Comment by Vooyage21** [comment]
use another host like heroku, if you want to deploy use heroku not vps. solution

**Comment by iamtalhaasghar** [comment]
This is a youtube-dlp related issue.

**Comment by tobocop2** [comment]
thank you @iamtalhaasghar !!!!
