### ISSUE TITLE
crash when searching

### ISSUE THREAD

**Issue by devcomputer** [mps-youtube/yewtube#1277]
yewtube crashes right after showing results.

**what I do:**
> $yt

> /anysearchterm

**The error**

> ERROR: [youtube] r7WI4A8N8dA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Exception in thread Thread-1 (_preload):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3463, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
>    return func(self, *args, **kwargs)
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
>    ie_result = ie.extract(url)
>  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 667, in extract
>    raise type(e)(e.orig_msg, **kwargs)
>yt_dlp.utils.RegexNotFoundError: [youtube] r7WI4A8N8dA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>    self.run()
>  File "/usr/lib/python3.10/threading.py", line 953, in run
>    self._target(*self._args, **self._kwargs)
>  File "/home/lab/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 189, in _preload
>    streamlist = get(song)
>  File "/home/lab/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 54, in get
>    ps = pafy.get_video_streams(ytid)
>  File "/home/lab/.local/lib/python3.10/site-packages/mps_youtube/pafy.py", line 43, in get_video_streams
>    info_dict = ydl.extract_info(ytid, download=False)
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1399, in extract_info
>    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1426, in wrapper
>    self.report_error(str(e), e.format_traceback())
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 950, in report_error
>    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
>  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 895, in trouble
>    raise DownloadError(message, exc_info)
>yt_dlp.utils.DownloadError: ERROR: [youtube] r7WI4A8N8dA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

## Issue / Suggestion

> search taylor
> /taylor

## Your Environment
> $ uname -a
> Linux mint 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

> $ yt-dlp -vU
>[debug] Command-line config: ['-vU']
>[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
>[debug] yt-dlp version master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds [644d84d77] (zip)
>[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-113-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
>[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 1.9.8, rtmpdump 2.4
>[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.6, websockets-10.4
>[debug] Proxy map: {}
>[debug] Request Handlers: urllib
>[debug] Loaded 1834 extractors
>[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
>Latest version: master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds
>yt-dlp is up to date (master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds)

> $ mpsyt --version
>Traceback (most recent call last):
>  File "/usr/bin/mpsyt", line 33, in <module>
>    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')())
>  File "/usr/bin/mpsyt", line 25, in importlib_load_entry_point
>    return next(matches).load()
>  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
>    return functools.reduce(getattr, attrs, module)
>AttributeError: module 'mps_youtube' has no attribute 'main'
>Error in sys.excepthook:
>Traceback (most recent call last):
>  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
>    with os.fdopen(os.open(pr_filename,
>FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mpsyt.1000.crash'
>
> Original exception was:
> Traceback (most recent call last):
>  File "/usr/bin/mpsyt", line 33, in <module>
>    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')())
>  File "/usr/bin/mpsyt", line 25, in importlib_load_entry_point
>    return next(matches).load()
>  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
>    return functools.reduce(getattr, attrs, module)
>AttributeError: module 'mps_youtube' has no attribute 'main'

> $ uname -a
> Linux mint 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

yewtube

**Comment by iamtalhaasghar** [comment]
looks like yt-dlp was outdated. Upgrade to latest version of yewtube and this will be fixed.
