### ISSUE TITLE
No streams available, exception in thread, NoneType object not subscriptable in streams.py

### ISSUE THREAD

**Issue by kkkaamis** [mps-youtube/yewtube#1280]
## Issue
Videos don't play, this error shows up. Sometimes it works, then goes back to not working.
_No streams available                                                                           [1/71>
> Exception in thread Thread-2 (_preload):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/devuan/.local/pipx/venvs/yewtube/lib/python3.11/site-packages/mps_youtube/streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
                   ~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable_

## Your Environment
Devuan linux, using pipx and mpv
<!--- Include as many relevant details about the environment you experienced the bug in -->
<!--- Run "mpsyt --version" and post your version information here --->
<!-- What version of the OS are you running, any other  -->
<!-- What music player are you using with mps-youtube, version? -->

**Comment by VanackSabbadium** [comment]
Same here.

Debian Sid, using pipx, mpv, python 3.12.4.

**Comment by suverino** [comment]
same issue here on two different machines.

Both use following environment:
Arch Linux, pipx, python 3.12.4, mpv, Yewtube 2.10.5

**Comment by avoidik** [comment]
at least audio:

```
set show_video False
```

**Comment by misterfish** [comment]
yewtube has been broken for about 2 weeks, due, I suspect, to a change made by Youtube in how the streams may be accessed. If you do a fresh install of yewtube then you may at least be able to get audio-only default streams.

youtube-dl and ytfzf still work. But ytfzf uses a different URL, which is not optimized for streaming, meaning it often gets stuck buffering, and seeking is a pain.

**Comment by VanackSabbadium** [comment]
It seems like Yewtube is somehow dead or rarely updated, so i don't think this is gonna be solved in a short time.

Does anyone know an alternative program?

**Comment by fgaz** [comment]
After a quick look at the source code, I think the issue is not in yewtube itself, but in the [youtube-search-python](https://github.com/alexmercerind/youtube-search-python) dependency, which is sadly [unmaintained](https://github.com/alexmercerind/youtube-search-python/issues/189).

**Comment by VanackSabbadium** [comment]
> After a quick look at the source code, I think the issue is not in yewtube itself, but in the [youtube-search-python](https://github.com/alexmercerind/youtube-search-python) dependency, which is sadly [unmaintained](https://github.com/alexmercerind/youtube-search-python/issues/189).

Alright, so we are basically doomed...

**Comment by thisIsTheFoxe** [comment]
I haven't run into this issue myself, but I did notice a comment about *youtube-search-python* from a contributor which might be helpful:

> youtube-search-python has been archived for months now but its still working. We'll port to another backend .i.e. pytube, invidious api when things will break. For now enjoy!

_Originally posted by @iamtalhaasghar in https://github.com/mps-youtube/yewtube/issues/1204#issuecomment-1650398979_

Maybe it is time to switch to a new new lib..

**Comment by fgaz** [comment]
Seems like it's working again (for me at least). Still, without a maintained search library, it's only a matter of time until it stops working once and for all.

**Comment by Likver** [comment]
i just installed yewtube, i have the same issue with videos but using ``set show_video false`` to only stream audio works

**Comment by iamtalhaasghar** [comment]
I can't recreate this on my end. Hence, closing. If this is is still happening pls create a new issue.

**Comment by kkkaamis** [comment]
I've had this problem twice since, and it goes away once I delete the mps-youtube config directory and reinstall. Idk
