### ISSUE TITLE
unable to play queries using yewtube

### ISSUE THREAD

**Issue by inspector3535** [mps-youtube/yewtube#1301]
Hey there, thanks for creating such a useful Yewtube player!  I was using it without any issue until today. searching works well but playback failes and shows the following error message:
OS: Microsoft Windows 10 pro
yewtube ver:                                                                 v2.12.0
player application: VLC
Exception in thread Thread-1 (_preload):
Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\site-packages\mps_youtube\streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
                   ~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-2 (_preload):
Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python312\Lib\site-packages\mps_youtube\streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
                   ~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Regards.

**Comment by Sarkar069** [comment]
I am experiencing the same issue as well.

**Comment by rottifant85** [comment]
I am also experiencing this issue on Linux.

**Comment by ElMiguel123** [comment]
same issue using debian12. Here is the error message after a simple search (no need to start a play)

Search results for jean-michel jarre                     [1/3>
  File "/usr/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
  File "/home/miguel/.local/pipx/venvs/yewtube/lib/python3.11/site-packages/mps_youtube/streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
                   ~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by iamtalhaasghar** [comment]
if this is still happening let me know. I am unable to recreate this on my end.

**Comment by inspector3535** [comment]
Hi again;
after your reply I checked once again but still the same on Windows 10.
YT gathers the search results but the playback failes with the same error message.
regards.

**Comment by inspector3535** [comment]
hello;
i'm very verry sorry, I missed the update. when I noticed that I have the previous version, I downloaded the latest .zip urgently and updated using setupfile.
the latest version works perfectly, please excuse me for this mistake.
