### ISSUE TITLE
Trouble playing videos

### ISSUE THREAD

**Issue by ryba3310** [mps-youtube/yewtube#1302]
Cannot play videos neither in vlc nor mpv, audio playback works correctly after updating nodejs from node-v14.15.4-linux to node-v18.20.5-linux. 

## Issue / Suggestion

```
Exception in thread Thread-18 (_preload):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryba/.local/lib/python3.10/site-packages/mps_youtube/streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
TypeError: 'NoneType' object is not subscriptable
```

yt > 'search for video' > enter number to play video

## Your Environment

```
cat /etc/*release
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
```

Running ```mpsyt --version```
```
yewtube version    : 2.12.0
yt_dlp version     : 2024.10.07
Python version     : 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/ryba/.config/mps-youtube
dbus               : 1.2.18
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_GB.UTF-8
env:LANGUAGE       : en_GB:en

```

Pop Os - Ubuntu 22.04

vlc

**Comment by terminaldweller** [comment]
Try downloading a video from youtube with `yt-dlp` or whatever you have that handles the youtube side and see if the problem persists.

**Comment by iamtalhaasghar** [comment]
if this is still happening let me know. I am unable to recreate this on my end. @ryba3310

**Comment by ryba3310** [comment]
Issue still persists. To be honest, I don't how see to approach this. Tried uninstalling and installing again and got dependency error message:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
librespot 0.0.9 requires requests==2.30.0, but you have requests 2.32.3 which is incompatible.
```
After second run there was no dependency error, smooth installation but still same error while running the app.
Probably something messed my python libraries/dependencies, no idea how to dig into that.
