### ISSUE TITLE
MPSYT won't start, Errno 13, Permission denied

### ISSUE THREAD

**Issue by daleobradovic** [mps-youtube/yewtube#491]
After installation, it was working.
When I've tried later, it won't start.

Tried to clear the cache.

Logs:

`
***_@**_*-X550VC:~$ mpsyt
WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python3/dist-packages/mps_youtube/**init**.py", line 2, in <module>
    init()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 867, in init
    init_readline()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 1068, in init_readline
    readline.read_history_file(g.READLINE_FILE)
PermissionError: [Errno 13] Permission denied

***_@**_*-X550VC:~$ youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
`

**Comment by ids1024** [comment]
Try `chown -r your_user_name ~/.config/mps-youtube`.

**Comment by aayushnul** [comment]
try installing youtube-dl from pip so that the warning is removed and next for permission try clearing old config at ~/.config/mps-youtube and reinstall the mps-youtube

**Comment by snehalparmar** [comment]
Thanks, removing the config file fix the issue.
