### ISSUE TITLE
mpsyt- error with nonnumeric port:

### ISSUE THREAD

**Issue by vinvasanth** [mps-youtube/yewtube#612]
Dear All

I install mpsyt on fedora when I made the recent update I cant able to play the link using any player. I can search music when I launch selected link,  mpsyt terminates automatically. I highly appreciate if any one suggest me a solution to fix this issue.

Have a good weekend.

Vince

PS: This is the error before I select a link to play

ERROR: Unable to download webpage: nonnumeric port: 'port' (caused by InvalidURL("nonnumeric port: 'port'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by vinvasanth** [comment]
mpsyt termnates with the following error

ERROR: Unable to download webpage: nonnumeric port: 'port' (caused by InvalidURL("nonnumeric port: 'port'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 151, in _playsong
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/streams.py", line 51, in get
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/util.py", line 202, in get_pafy
  File "/usr/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: Unable to download webpage: nonnumeric port: 'port' (caused by InvalidURL("nonnumeric port: 'port'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/main.py", line 143, in main
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/main.py", line 65, in matchfunction
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/commands/play.py", line 87, in play
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 42, in play_range
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 163, in _playsong
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 163, in _playsong
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 163, in _playsong
  File "/usr/lib/python3.5/site-packages/mps_youtube-0.2.7.1-py3.5.egg/mps_youtube/player.py", line 178, in _playsong

**Comment by ids1024** [comment]
I've never seen that error before. Do you have the latest version of youtube-dl?

**Comment by vinvasanth** [comment]
Hi 

Thank you for your comments
I do have latest version of youtube-dl-2017.04.02. pip3

Thanks
Vince
