### ISSUE TITLE
No matching distribution found for pygobject

### ISSUE THREAD

**Issue by Linux-joy** [mps-youtube/yewtube#645]
Dear all,

my mps_youtube-Version is 0.2.7.1, my pafy-Version is 0.5.3.1.

I followed the installation instructions and performed the following command from inside of a virtual environment on Ubuntu 14.04:

`$ bin/pip3 install pygobject`

However, it results in the following error:

```
Collecting pygobject
  Could not find a version that satisfies the requirement pygobject (from versions: )
No matching distribution found for pygobject

```

Any ideas what is happening here?

Thanks.

**Comment by Razesdark** [comment]
By the looks of it, PyGObject has been removed from the Python Package Index.

https://pypi.python.org/pypi/PyGObject
I have searched around for a few minutes but wasn't able to find out more.

**Comment by Linux-joy** [comment]
Many thanks for you, Razesdark!

Perhaps, couldn't there be an equivalent substitute for PyGObject?

**Comment by Linux-joy** [comment]
I have found this: 
[https://pygobject.readthedocs.io/en/latest/faq.html](https://pygobject.readthedocs.io/en/latest/faq.html):

> ## Frequently Asked Questions
> ### Can I use PyGObject with virtualenv?
> 
> To use PyGObject in a virtualenv you have to install it globally and use --system-site-packages.
> 
> ```
> virtualenv --system-site-packages --python=python2 venv
> source venv/bin/activate
> python -c "import gi"
> deactivate
> 
> ```
> You can also symlink “gi” and “cairo” in the virtualenv, but this is not supported.
> ### What about the PyGObject package on PyPI?
> 
> The [PyGObject](https://pypi.python.org/pypi/PyGObject) on PyPI is the old PyGObject 2 and should not be used in new projects.
> ### Can I install PyGObject through pip somehow?
> 
> You can install directly from git:
> 
> ```
> virtualenv --system-site-packages --python=python2 venv
> source venv/bin/activate
> pip install "git+https://git.gnome.org/browse/pygobject@3.22.0"
> python -c "import gi"
> deactivate
> 
> ```
> Note that this uses autotools internally and not distutils.
>
> (...)
>
>
From https://virtualenv.pypa.io/en/stable/userguide/#the-system-site-packages-option :

> ### The `--system-site-packages` Option
> 
> If you build with `virtualenv --system-site-packages ENV`, your virtual environment will inherit packages from `/usr/lib/python2.7/site-packages` (or wherever your global site-packages directory is).
> 
> This can be used if you have control over the global site-packages directory, and you want to depend on the packages there. If you want isolation from the global system, do not use this flag.
> 
>

From https://virtualenv.pypa.io/en/stable/reference/#cmdoption-system-site-packages :
>
> ###  `--system-site-packages`
> 
>     Give the virtual environment access to the global site-packages.
> 
>
From https://virtualenv.pypa.io/en/stable/reference/#cmdoption-p :
>
> ### `-p PYTHON_EXE`, `--python=PYTHON_EXE`
> 
>     The Python interpreter to use, e.g., –python=python2.5 will use the python2.5 interpreter to create the new environment. The default is the interpreter that virtualenv was installed with (like `/usr/bin/python`)
>




|
|
Now, i have some Experience:
|
|




First, I tried  
### Can I use PyGObject with virtualenv?


 
```
xor@xor-ms-0:~$ virtualenv --system-site-packages --python=python2 venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/xor/venv/bin/python2
Also creating executable in /home/xor/venv/bin/python
Installing setuptools, pip, wheel...done.

xor@xor-ms-0:~$ source venv/bin/activate
(venv) xor@xor-ms-0:~$ python -c "import gi"
(venv) xor@xor-ms-0:~$ deactivate


xor@xor-ms-0:~$ ls -al /home/xor/venv/lib/python2.7/site-packages
insgesamt 44
drwxrwxr-x  9 xor xor 4096 Jun 11 01:31 .
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 ..
-rw-rw-r--  1 xor xor  126 Jun 11 01:31 easy_install.py
-rw-rw-r--  1 xor xor  315 Jun 11 01:31 easy_install.pyc
drwxrwxr-x 10 xor xor 4096 Jun 11 01:31 pip
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 pip-9.0.1.dist-info
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 pkg_resources
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 setuptools
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 setuptools-36.0.1.dist-info
drwxrwxr-x  5 xor xor 4096 Jun 11 01:31 wheel
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 wheel-0.29.0.dist-info
xor@xor-ms-0:~$ ls -al /home/xor/venv/local/lib/python2.7/site-packages
insgesamt 44
drwxrwxr-x  9 xor xor 4096 Jun 11 01:31 .
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 ..
-rw-rw-r--  1 xor xor  126 Jun 11 01:31 easy_install.py
-rw-rw-r--  1 xor xor  315 Jun 11 01:31 easy_install.pyc
drwxrwxr-x 10 xor xor 4096 Jun 11 01:31 pip
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 pip-9.0.1.dist-info
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 pkg_resources
drwxrwxr-x  4 xor xor 4096 Jun 11 01:31 setuptools
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 setuptools-36.0.1.dist-info
drwxrwxr-x  5 xor xor 4096 Jun 11 01:31 wheel
drwxrwxr-x  2 xor xor 4096 Jun 11 01:31 wheel-0.29.0.dist-info
xor@xor-ms-0:~$ ls -al /home/xor/venv/bin
insgesamt 3316
drwxrwxr-x 2 xor xor    4096 Jun 11 01:31 .
drwxrwxr-x 5 xor xor    4096 Jun 11 01:31 ..
-rw-rw-r-- 1 xor xor    2073 Jun 11 01:31 activate
-rw-rw-r-- 1 xor xor    1015 Jun 11 01:31 activate.csh
-rw-rw-r-- 1 xor xor    2169 Jun 11 01:31 activate.fish
-rw-rw-r-- 1 xor xor    1137 Jun 11 01:31 activate_this.py
-rwxrwxr-x 1 xor xor     244 Jun 11 01:31 easy_install
-rwxrwxr-x 1 xor xor     244 Jun 11 01:31 easy_install-2.7
-rwxrwxr-x 1 xor xor     216 Jun 11 01:31 pip
-rwxrwxr-x 1 xor xor     216 Jun 11 01:31 pip2
-rwxrwxr-x 1 xor xor     216 Jun 11 01:31 pip2.7
lrwxrwxrwx 1 xor xor       7 Jun 11 01:31 python -> python2
-rwxrwxr-x 1 xor xor 3341384 Jun 11 01:31 python2
lrwxrwxrwx 1 xor xor       7 Jun 11 01:31 python2.7 -> python2
-rwxrwxr-x 1 xor xor    2332 Jun 11 01:31 python-config
-rwxrwxr-x 1 xor xor     223 Jun 11 01:31 wheel
xor@xor-ms-0:~$ ls -al /home/xor/venv/local/bin
lrwxrwxrwx 1 xor xor 18 Jun 11 01:31 /home/xor/venv/local/bin -> /home/xor/venv/bin
xor@xor-ms-0:~$ 



xor@xor-ms-0:~$ apt show python3-gi 
Package: python3-gi
...
Version: 3.12.0-1ubuntu1
Replaces: python3-gobject
Provides: python3-gobject
Depends: python3 (<< 3.5), python3 (>= 3.4~), libc6 (>= 2.14), libgirepository-1.0-1 (>= 1.33.10), libglib2.0-0 (>= 2.38.0), gir1.2-glib-2.0 (>= 1.35.9)
Conflicts: python3-gobject
...
Origin: Ubuntu
Supported: 5y
Task: standard, kubuntu-active, kubuntu-active, mythbuntu-frontend, mythbuntu-desktop, mythbuntu-backend-slave, mythbuntu-backend-master, mythbuntu-backend-master
APT-Manual-Installed: yes
APT-Sources: http://de.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
Description: Python 3 bindings for gobject-introspection libraries
 Die Abstraktionsschicht GObject ermöglicht Ihnen, mit einem zu vielen
 Sprachen kompatiblen Objektparadigma zu programmieren. GObject ist Teil
 von Glib, der Kernbibliothek für »den Bau« von GTK+ und GNOME.
|
|
xor@xor-ms-0:~$ apt show python-gi 
Package: python-gi
...
Source: pygobject
Version: 3.12.0-1ubuntu1
Replaces: python-gobject (<< 3.0.2-4)
Provides: python2.7-gi
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libc6 (>= 2.14), libgirepository-1.0-1 (>= 1.33.10), libglib2.0-0 (>= 2.38.0), gir1.2-glib-2.0 (>= 1.35.9)
Suggests: python-gi-cairo
Breaks: python-aptdaemon (<< 1.0), python-gobject (<< 3.0.2-4), python-nautilus (<= 1.1-1), software-center (<= 5.6.0-0ubuntu2)
Download-Size: 192 kB
Homepage: https://wiki.gnome.org/PyGObject
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y
Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, kubuntu-full, kubuntu-active, kubuntu-active-desktop, kubuntu-active-full, kubuntu-active, edubuntu-desktop, edubuntu-usb, xubuntu-desktop, mythbuntu-frontend, mythbuntu-desktop, mythbuntu-backend-slave, mythbuntu-backend-master, mythbuntu-backend-master, lubuntu-core, ubuntustudio-desktop, ubuntu-gnome-desktop
APT-Manual-Installed: no
APT-Sources: http://de.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
Description: Python-2.x-Anbindungen für »gobject-introspection«-Bibliotheken
 Die Abstraktionsschicht GObject ermöglicht Ihnen, mit einem zu vielen
 Sprachen kompatiblen Objektparadigma zu programmieren. GObject ist Teil
 von Glib, der Kernbibliothek für »den Bau« von GTK+ und GNOME.
 .

```


Then, I tried:
### Can I install PyGObject through pip somehow?




```
xor@xor-ms-0:~$ virtualenv --system-site-packages --python=python2 venv2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/xor/venv2/bin/python2
Also creating executable in /home/xor/venv2/bin/python
Installing setuptools, pip, wheel...done.


xor@xor-ms-0:~$ source venv2/bin/activate
(venv2) xor@xor-ms-0:~$ pip install "git+https://git.gnome.org/browse/pygobject@3.22.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.22.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.22.0) to /tmp/pip-fktIYe-build
  Error [Errno 2] Datei oder Verzeichnis nicht gefunden while executing command git clone -q https://git.gnome.org/browse/pygobject /tmp/pip-fktIYe-build
Cannot find command 'git'


(venv2) xor@xor-ms-0:~$ sudo apt-get install git 
...
...



(venv2) xor@xor-ms-0:~$ pip install "git+https://git.gnome.org/browse/pygobject@3.22.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.22.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.22.0) to /tmp/pip-CR_JxE-build
Installing collected packages: pygobject
  Found existing installation: pygobject 3.12.0
    Not uninstalling pygobject at /usr/lib/python2.7/dist-packages, outside environment /home/xor/venv2
  Running setup.py install for pygobject ... error
    Complete output from command /home/xor/venv2/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-CR_JxE-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kbknPl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/venv2/include/site/python2.7/pygobject:
    running install
    running build
    You need to install gnome-common.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-CR_JxE-build/setup.py", line 103, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/xor/venv2/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-CR_JxE-build/setup.py", line 59, in run
        cwd=builddir)
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-CR_JxE-build/autogen.sh', 'PYTHON=/home/xor/venv2/bin/python2', '--prefix=/tmp/pip-CR_JxE-build/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
  Can't rollback pygobject, nothing uninstalled.
Command "/home/xor/venv2/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-CR_JxE-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kbknPl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/venv2/include/site/python2.7/pygobject" failed with error code 1 in /tmp/pip-CR_JxE-build/




(venv2) xor@xor-ms-0:~/venv2$ deactivate




(python-test) xor@xor-ms-0:~/Programme/python-test$ deactivate
xor@xor-ms-0:~/Programme/python-test$ cd


xor@xor-ms-0:~$ sudo apt-get install gnome-common
...
...
...

xor@xor-ms-0:~$ source /home/xor/Programme/python-test/bin/activate
(python-test) xor@xor-ms-0:~$ cd /home/xor/Programme/python-test
(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://git.gnome.org/browse/pygobject@3.22.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.22.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.22.0) to /tmp/pip-xrkoqtxw-build
Installing collected packages: pygobject
  Running setup.py install for pygobject ... error
    Complete output from command /home/xor/Programme/python-test/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-xrkoqtxw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j1z7brf6-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/Programme/python-test/include/site/python3.4/pygobject:
    running install
    running build
    /usr/bin/gnome-autogen.sh
    checking for autoreconf >= 2.53...
      testing autoreconf... found 2.69
    checking for pkg-config >= 0.14.0...
      testing pkg-config... found 0.26
    Checking for required M4 macros...
    ...
    No package 'libffi' found
    ...
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    ...
    Alternatively, you may set the environment variables FFI_CFLAGS
    and FFI_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-xrkoqtxw-build/setup.py", line 103, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xor/Programme/python-test/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-xrkoqtxw-build/setup.py", line 59, in run
        cwd=builddir)
      File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-xrkoqtxw-build/autogen.sh', 'PYTHON=/home/xor/Programme/python-test/bin/python3.4', '--prefix=/tmp/pip-xrkoqtxw-build/build/temp.linux-x86_64-3.4/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/xor/Programme/python-test/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-xrkoqtxw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j1z7brf6-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/Programme/python-test/include/site/python3.4/pygobject" failed with error code 1 in /tmp/pip-xrkoqtxw-build/


(python-test) xor@xor-ms-0:~/Programme/python-test$ deactivate
xor@xor-ms-0:~/Programme/python-test$ cd


xor@xor-ms-0:~$ sudo apt-get install libffi-dev
Paketlisten werden gelesen... Fertig



xor@xor-ms-0:~$ source /home/xor/Programme/python-test/bin/activate
(python-test) xor@xor-ms-0:~$ cd /home/xor/Programme/python-test
(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://git.gnome.org/browse/pygobject@3.22.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.22.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.22.0) to /tmp/pip-km5yhdui-build
Installing collected packages: pygobject
  Running setup.py install for pygobject ... error
    Complete output from command /home/xor/Programme/python-test/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-km5yhdui-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u_z8fxtt-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/Programme/python-test/include/site/python3.4/pygobject:
    running install
    running build
    /usr/bin/gnome-autogen.sh
 ...
    checking for GIO... yes
    checking for GI... no
    configure: error: Package requirements (glib-2.0 >= 2.38.0
        gobject-introspection-1.0 >= 1.46.0
    ) were not met:
    
    No package 'gobject-introspection-1.0' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables GI_CFLAGS
    and GI_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-km5yhdui-build/setup.py", line 103, in <module>
        'build_ext': BuildExt,
  
    ----------------------------------------
Command "/home/xor/Programme/python-test/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-km5yhdui-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u_z8fxtt-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/Programme/python-test/include/site/python3.4/pygobject" failed with error code 1 in /tmp/pip-km5yhdui-build/


(python-test) xor@xor-ms-0:~/Programme/python-test$ deactivate
xor@xor-ms-0:~/Programme/python-test$ cd


xor@xor-ms-0:~$ sudo apt-get install gobject-introspection
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
...
python-markupsafe (0.18-1build2) wird eingerichtet ...
python-mako (0.9.1-1) wird eingerichtet ...
gobject-introspection (1.40.0-1ubuntu0.2) wird eingerichtet ...


xor@xor-ms-0:~$ source /home/xor/Programme/python-test/bin/activate
(python-test) xor@xor-ms-0:~$ cd /home/xor/Programme/python-test
(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://git.gnome.org/browse/pygobject@3.22.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.22.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.22.0) to /tmp/pip-0br_1eox-build
Installing collected packages: pygobject
  Running setup.py install for pygobject ... error
    Complete output from command /home/xor/Programme/python-test/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-0br_1eox-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-n9w4rlhx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xor/Programme/python-test/include/site/python3.4/pygobject:
    running install
    running build
    /usr/bin/gnome-autogen.sh
    checking for autoreconf >= 2.53...
      testing autoreconf... found 2.69
    checking for pkg-config >= 0.14.0...
      testing pkg-config... found 0.26
   2)
    checking for FFI... yes
    checking for GIO... yes
    checking for GI... no
    configure: error: Package requirements (glib-2.0 >= 2.38.0
        gobject-introspection-1.0 >= 1.46.0
    ) were not met:
    
    No package 'gobject-introspection-1.0' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables GI_CFLAGS
    and GI_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    ...
...

(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://git.gnome.org/browse/pygobject@3.12.0"
Collecting git+https://git.gnome.org/browse/pygobject@3.12.0
  Cloning https://git.gnome.org/browse/pygobject (to 3.12.0) to /tmp/pip-uw3jfo0d-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xor/Programme/python-test/lib/python3.4/tokenize.py", line 438, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-uw3jfo0d-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-uw3jfo0d-build/


(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://github.com/GNOME/pygobject/tree/6392b2727e7ed391683bebbf69fbc8b474e99a5f"
Collecting git+https://github.com/GNOME/pygobject/tree/6392b2727e7ed391683bebbf69fbc8b474e99a5f
  Cloning https://github.com/GNOME/pygobject/tree/6392b2727e7ed391683bebbf69fbc8b474e99a5f to /tmp/pip-g5a3u9go-build
fatal: repository 'https://github.com/GNOME/pygobject/tree/6392b2727e7ed391683bebbf69fbc8b474e99a5f/' not found
Command "git clone -q https://github.com/GNOME/pygobject/tree/6392b2727e7ed391683bebbf69fbc8b474e99a5f /tmp/pip-g5a3u9go-build" failed with error code 128 in None


(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install "git+https://git.gnome.org/browse/pygobject@3.17.90"Collecting git+https://git.gnome.org/browse/pygobject@3.17.90
  Cloning https://git.gnome.org/browse/pygobject (to 3.17.90) to /tmp/pip-oooqxzj9-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xor/Programme/python-test/lib/python3.4/tokenize.py", line 438, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-oooqxzj9-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oooqxzj9-build/


(python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 -V
pip 9.0.1 from /home/xor/Programme/python-test/lib/python3.4/site-packages (python 3.4)
(

python-test) xor@xor-ms-0:~/Programme/python-test$ bin/pip3 install --upgrade pip
Requirement already up-to-date: pip in ./lib/python3.4/site-packages


(python-test) xor@xor-ms-0:~/Programme/python-test$ deactivate
xor@xor-ms-0:~/Programme/python-test$ source venv2/bin/activate
bash: venv2/bin/activate: Datei oder Verzeichnis nicht gefunden
xor@xor-ms-0:~/Programme/python-test$ cd
xor@xor-ms-0:~$ source venv2/bin/activate
(venv2) xor@xor-ms-0:~$ cd ~/venv2


(venv2) xor@xor-ms-0:~/venv2$ bin/pip install "git+https://git.gnome.org/browse/pygobject@3.17.90"
Collecting git+https://git.gnome.org/browse/pygobject@3.17.90
  Cloning https://git.gnome.org/browse/pygobject (to 3.17.90) to /tmp/pip-EBM8aB-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-EBM8aB-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-EBM8aB-build/


(venv2) xor@xor-ms-0:~/venv2$ bin/pip install "https://git.gnome.org/browse/pygobject@3.17.90"
Collecting https://git.gnome.org/browse/pygobject@3.17.90
/home/xor/venv2/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/xor/venv2/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  HTTP error 404 while getting https://git.gnome.org/browse/pygobject@3.17.90
  Could not install requirement https://git.gnome.org/browse/pygobject@3.17.90 because of error 404 Client Error: Not found for url: https://git.gnome.org/browse/pygobject@3.17.90
Could not install requirement https://git.gnome.org/browse/pygobject@3.17.90 because of HTTP error 404 Client Error: Not found for url: https://git.gnome.org/browse/pygobject@3.17.90 for URL https://git.gnome.org/browse/pygobject@3.17.90


(venv2) xor@xor-ms-0:~/venv2$ pip install "git+https://git.gnome.org/browse/pygobject@3.17.90"
Collecting git+https://git.gnome.org/browse/pygobject@3.17.90
  Cloning https://git.gnome.org/browse/pygobject (to 3.17.90) to /tmp/pip-3Yc2vo-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-3Yc2vo-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3Yc2vo-build/


(venv2) xor@xor-ms-0:~/venv2$ deactivate
xor@xor-ms-0:~/venv2$ cd
xor@xor-ms-0:~$ 

```




Summary:

 - I had to install git, gnome-common, libffi-dev, gobject-introspection.
 - (For dbus-python, I had to install pkg-config, libdbus-1-dev, libdbus-glib-1-dev brfore).
 - There are no "gi"- or "gobject"-files in the virtual enviroment, probably as they are located in /usr/lib/python2.7/dist-packages and not in /usr/lib/python2.7/site-packages.
 - Package requirement gobject-introspection-1.0 >= 1.46.0 is too high, my package is version 1.40!
 - Download of an older version of pgobject directly from GitHub causes error "No such file or directory: '/tmp/pip-EBM8aB-build/setup.py'".
 - Later, I will try this:
> You can also symlink “gi” and “cairo” in the virtualenv, but this is not supported.

**Comment by Linux-joy** [comment]
Dear all,

>     Later, I will try this:
>> You can also symlink “gi” and “cairo” in the virtualenv, but this is not supported.

Oh no, I am not any more keen on this!

I will try the recommended way of installation via system-wide pip3. The packages "python3-dbus" and "python3-gi" are already installed.

Thanks.

**Comment by zhelding** [comment]
Perhaps you can just install pygobject from your distribution's repositories? 

Details for a number of distributions are available [here](https://pygobject.readthedocs.io/en/latest/getting_started.html).

I was able to do this without any difficulty for Arch Linux.

**Comment by Linux-joy** [comment]
> Perhaps you can just install pygobject from your distribution's repositories?
Yes, as I already wrote one post before, is the package "python3-gi" already installed, and it works, but of course NOT in a virtual enviroment.

**Comment by Linux-joy** [comment]
> Perhaps you can just install pygobject from your distribution's repositories?

Yes, as I already wrote one post before, is the package "python3-gi" already installed, and it works, but of course NOT in a virtual enviroment.
