### ISSUE TITLE
Unable to Playback Videos

### ISSUE THREAD

**Issue by ghost** [mps-youtube/yewtube#655]
Hi, 

I just downloaded and installed MPS-Youtube using [sudo] pip3.6 install mps-youtube, however, upon attempting to play back any video in VLC. Yes, I set my player.

I get the following error(s): 
Sorry, this track is not available                                                                 
> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/mps_youtube-0.2.7.1-py3.6.egg/mps_youtube/streams.py", line 171, in _preload
    streamlist = get(song)
  File "/usr/lib/python3.6/site-packages/mps_youtube-0.2.7.1-py3.6.egg/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.6/site-packages/mps_youtube-0.2.7.1-py3.6.egg/mps_youtube/util.py", line 203, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3.6/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3.6/site-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.6/site-packages/pafy/backend_internal.py", line 75, in _fetch_basic
    sm_ciphertag = "s" in self.sm[0]
IndexError: list index out of range

Prior knowledge leads me to believe that this is an error at the python level as I've had similar errors when attempting to use the program geeknote - which installs in a very similar fashion to MPS-Youtube.

My base OS is Arch Linux for reference.

Is anyone else having similar issues like this?

**Comment by tmerr** [comment]
I am also running arch, could you give me exact steps of how I can reproduce this issue at home? I don't know how you have mps-youtube configured or what video I should be downloading. And could you also post the output of `pip freeze`?

**Comment by ids1024** [comment]
`sudo pacman -S youtube-dl` should fix it.

You can also install mps-youtube through pacman if you'd like; it's in the community repository.
