### ISSUE TITLE
crash with the search word "disturbed"

### ISSUE THREAD

**Issue by mskrs** [mps-youtube/yewtube#680]
Output:

Searching for 'disturbed'                                                                                                                    
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/commands/search.py", line 212, in search
    _search(term, query, msg, failmsg)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/commands/search.py", line 41, in _search
    loadmsg=loadmsg)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/commands/songlist.py", line 56, in paginatesongs
    songs = func[s:e]
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/commands/search.py", line 28, in iter_songs
    for song in get_tracks_from_json(wdata2):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/commands/search.py", line 342, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 9: expected str instance, dict found

**Comment by Razesdark** [comment]
Check out #666 and #663. This bug should be gone on the `develop` branch.
