### ISSUE TITLE
Unable to download or view anything

### ISSUE THREAD

**Issue by prateek-dhanuka** [mps-youtube/yewtube#688]
I just installed mps-youtube and nothing seems to work. No matter what I try to do, ,the application crashes with
```
Traceback (most recent call last):                                              
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.7.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/player.py", line 148, in _playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable
```
Can anybody tell me what to do?

**Comment by kraetzin** [comment]
If you haven't already, try installing from the develop branch. To do so run:

`sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git`

This seems to solve most problems.

**Comment by mcevzar** [comment]
I have the same problem, tried upgrading youtube-dl and installing from development branch as instructed, to no effect.

Any other suggestions?
