### ISSUE TITLE
Int conversion error in streams.py when attempting to play audio/video.

### ISSUE THREAD

**Issue by 3lpsy** [mps-youtube/yewtube#756]
I attempted to play a youtube live stream ($ mpsyt playurl https://www.youtube.com/watch?v=jsdCrt97_eU), and received an int conversion error. It happens when using CLI menu as well.

Environment:
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.09.11
Python version     : 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.2.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/aaa/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

Player: mpv

Error:
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/commands/play.py", line 105, in play_url
    play(override, "1", "_")
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/commands/play.py", line 85, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 41, in play_range
    returncode = _playsong(song, override=override)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/player.py", line 208, in _playsong
    size = streams.get_size(song.ytid, stream['url'])
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/streams.py", line 133, in get_size
    stream['size'] = _get_content_length(url, preloading=preloading)
  File "/usr/local/lib/python3.6/site-packages/mps_youtube/streams.py", line 146, in _get_content_length
    return int(cl)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by gtoast** [comment]
Getting same issue here using the command line app, installed via apt on Ubuntu 16.10 

```
Exception in thread Thread-6:   
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 178, in _preload
    get_size(ytid, stream['url'], preloading=True)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 133, in get_size
    stream['size'] = _get_content_length(url, preloading=preloading)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 146, in _get_content_length
    return int(cl)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by vn-ki** [comment]
Try the latest code in develop.

**Comment by Razesdark** [comment]
Maybe its time to do some extensive testing of the current dev version and posting a new version?

**Comment by Ferada** [comment]
Encountered that just now, in release 0.2.8, but, that code's still in `develop`:

```
...
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/streams.py", line 187, in _preload
    get_size(ytid, stream['url'], preloading=True)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/streams.py", line 142, in get_size
    stream['size'] = _get_content_length(url, preloading=preloading)
  File "/usr/local/lib/python3.6/dist-packages/mps_youtube/streams.py", line 155, in _get_content_length
    return int(cl)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
...
```

The try/catch block has a comment that it should fail silently, but then I don't quite see why it was logging it loudly.
