### ISSUE TITLE
not working for some links -- _get_metadata() problem

### ISSUE THREAD

**Issue by tungli** [mps-youtube/yewtube#826]
Hi,
for some songs my mps-youtube ver. 0.2.8 could no get through the `util._get_metadata()` function called from `_launch_player()` in player.py. It displayed no error message, just skipped the song.

After a lot of time I was able to notice that for some reason `_get_metadata()` returned `None` for songs that work and otherwise just doesn't play the song at all.

I fixed it by returning `None` early in util.py:
```
def _get_metadata(song_title) :
    ''' Get metadata from a song title '''

    return None
```
This is rather brute-force and I am not a Python user so I don't really understand the code.
Does somebody experience this as well or knows why is it happenning?
Thanks

**Comment by ritiek** [comment]
Hi, thanks for the report! Could you provide us a sample song where this problem happens?

**Comment by tungli** [comment]
Yes, although it happened more often than not.

Examples that worked fine:
```
https://youtube.com/watch?v=mZ2ZWLXvZ3Y
https://youtube.com/watch?v=AmOiIs_v6EE
```

Examples that did not play:
```
https://youtube.com/watch?v=iB9YYC-8jwY
https://youtube.com/watch?v=-tiCO1t8HFA
https://youtube.com/watch?v=N7BFBW3psp0
```

**Comment by ritiek** [comment]
I haven't been able to reproduce this problem. It works fine for me irrespective of what gets returned from `util._get_metadata()`. @tungli If you're still here, what player are you using?

**Comment by tungli** [comment]
I am aware that this might not be reproducible since I haven't seen other issues and you run into the problem right away, if you happen to have it...
I do not understand why it is happening, just wanted to report if someone ever happens to run into something similar.

To answer your question though, the issue was totally player independent.

**Comment by tungli** [comment]
With @lousapetr we have looked more deeply into this issue and we found out that something bizarre is happening.
The problem can be traced further to the `_get_metadata_from_lastfm()` function in `util`, particularly to the line with `json.loads()` call.

Testing with `https://youtube.com/watch?v=V1O3a-ccLaA` we enabled the debug_mode in `g.py` and inserted prints to `_get_metadata_from_lastfm()` and modified the  input of `json.loads()` to string (default was 'bytes' (b'string') ):
```
#print( json.loads(resp.read()))    #this simply fails to play without any error
print( json.loads(resp.read().decode('utf-8')))
data = json.loads(resp.read().decode('utf-8'))
#import requests         #fix
#data = requests.get(url).json()
print('TEST')
```
Weirdly this prints `data` but not the 'TEST' string.
The traceback error is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/player.py", line 50, in play_range
    returncode = _playsong(song, stream, video, override=override, softrepeat=softrepeat)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/player.py", line 240, in _playsong
    returncode = _launch_player(song, songdata, cmd)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/player.py", line 392, in _launch_player
    metadata = util._get_metadata(song.title)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/util.py", line 502, in _get_metadata
    metadata = _get_metadata_from_lastfm(t[0], t[1])
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/util.py", line 522, in _get_metadata_from_lastfm
    data = json.loads(resp.read().decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**Conclusion**
The *silent* error is caused by the `json.loads()` when it is passed a 'bytes'-string. This was tested outside the mpsyt package by importing json in python3.5 with the input from the `resp` variable and it gave a *traceback* 'TypeError'. 
When passed a regular string, it fails only when passed to a variable (`print()` works). Tested outside mpsyt package it works fine.

As indicated in the code above, importing and using the `requests` package solves the issue completely.
(The solution from: https://stackoverflow.com/questions/16573332/jsondecodeerror-expecting-value-line-1-column-1-char-0)

**Comment by rien333** [comment]
@tungli Whoops, this is probably some of the code I wrote. I will fix it ASAP.

**Comment by rien333** [comment]
I think a good way to avoid further problems might be to handle this metadata call through [pylast](https://github.com/pylast/pylast), which was recently added as a optional dependency to this project. I'll see if I can fix it, with or without pylast.

**Comment by tungli** [comment]
I still don't get why assignment to variable **inside** the package environment can cause an error :laughing:. If you know why this is happening, please tell me, I'm curious.

**Comment by vn-ki** [comment]
@tungli I think this issue is already fixed in `develop` branch. Can you try it?

**Comment by rien333** [comment]
I tried it, didn't work for me. Not across all of my machines at least. @tungli's fix did work on said broken machines though.

**Comment by xobes** [comment]
I'm using python 3.4

The problem is that _get_metadata_from_lastfm calls resp.read() directly in the json.load(s) -- and the r
resp.read() returns bytes.

I changed that to:
```
    import chardet
    r = resp.read()
    r = r.decode(chardet.detect(r)["encoding"])
    data = json.loads(r)
```

Installing latest dev (per above) did not work as it was broken in all new ways for me.
 
Here's the actual solution that's in the latest dev branch:

https://github.com/mps-youtube/mps-youtube/commit/7fa2cfdd94d11d2e6d855a5c7acea07522687325

furthermore, the _get_metadata_from_lastfm  function says at the top that it's going to "try" but then is not in a try statement at that level -- and for whatever reason, exception handlers don't log to the debug channel when they are triggered, and the main interface casually hides the exceptions of TypeError.
