### ISSUE TITLE
mpsyt desn't work with zsh

### ISSUE THREAD

**Issue by againpino** [mps-youtube/yewtube#868]
Since I installed zsh in my terminal every tame I try to run mpsyt it give me this message:

Traceback (most recent call last):
   File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()                            
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point  
    return get_distribution(dist).load_entry_point(group, name)                                     
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point 
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load             
    return self.resolve() 
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve          
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                           
  File "/usr/lib/python3.6/site-packages/mps_youtube/__init__.py", line 9, in <module>              
    from . import main
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 45, in <module>                 
     locale.setlocale(locale.LC_ALL, "")  # for date formatting                                       
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale                                    
   return _setlocale(category, locale)
locale.Error: unsupported locale setting

mspsyt version : 0.2.8.1
OS: Antergos

**Comment by Razesdark** [comment]
This is probably because you have set a locale which you don't have available.
run something like `set | grep LC_ALL` to see what locale has been set, then run `locale -a` and verify the presence of your set locale against that list. Be wary that it has to match the `.utf-8` part as well.

**Comment by iamtalhaasghar** [comment]
was fixed in ecd117ca1ef753509b78082d6f919c9bc2b1756b
