### ISSUE TITLE
Music Does Not Play

### ISSUE THREAD

**Issue by asddsaz** [mps-youtube/yewtube#887]
**Errors:**
```
Traceback (most recent call last):                                                           
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3450, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3543, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 2104, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```
Steps to Create:

`mpsyt`
`search Pink Floyd`
`1`

Edit:

I also get:

```
Search results for Pink Floyd                                         [1/27>
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```
OS: Elementary OS

**Comment by ritiek** [comment]
Same problem as #861?
