### ISSUE TITLE
 "token" parameter not in video info for unknown reason;

### ISSUE THREAD

**Issue by klopsi** [mps-youtube/yewtube#981]
Token error on all videos

ERROR: t1r-bJBgKWA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

> youtube-dl --version
2019.04.30

mpsyt: Fresh Git Clone from 2 minutes ago

 ./mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.04.17
Python version     : 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.19.0-4-amd64-x86_64-with-debian-10
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/monkeybutt/.config/mps-youtube
env:TERM           : rxvt-unicode-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US.UTF-8

**Comment by klopsi** [comment]
another example error output
youtube-dl is latest
Projects/youtube-dl# curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

-----------------------------------------------------------



    MST3K-Broadcast Editions: 602-Invasion USA [2:03:15]
                                                                          [1/20>
ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: ljHjbrZ02oA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/blap/.local/lib/python3.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: X-yndUKytVU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/main.py", line 148, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 49, in play_range
    video, stream = stream_details(song, override=override, softrepeat=softrepeat)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 171, in stream_details
    return stream_details(song, failcount=failcount, override=override, softrepeat=softrepeat)
  File "/home/blap/.local/lib/python3.7/site-packages/mps_youtube/player.py", line 186, in stream_details
    cached = g.streams[song.ytid]
KeyError: 'X-yndUKytVU'
monkey@butt:~ $

**Comment by vol-2** [comment]
I'm not 100% sure this will help you, but I was able to fix a "no token" issue with my installation by installing YouTube-dl using pip. Apparently, mps-youtube need the python version of youtube-dl, amd it specifically looks for it in the location that pip puts it in. I figured this out by searching this git, so if you need a better explanation, search this page more and you'll see that. If that isn't the issue, then I don't know.

**Comment by ianforcements** [comment]
Hi, I have this same issue - I have used pip to install youtube-dl version 2019.05.20, however mpsyt -v shows that the version is 2019.04.01

How can I make mpsyt look in the right location for youtube-dl?

**Comment by derWahnsinn** [comment]
Hi, I don't know if your issue still exists - I figured out a way how it works for me:

I had youtube-dl installed as well, but the python module wasn't the newest one, I upgraded it using pip:

`sudo pip3 install -U youtube_dl
`
hope it helps!
